apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: etcd-backup
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - /usr/local/bin/backup.sh
            image: ghcr.io/adfinis/kubernetes-etcd-backup:main
            imagePullPolicy: Always
            name: etcd-backup
            resources:
              requests:
                cpu: 500m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 512Mi
            envFrom:
            - configMapRef:
                name: backup-config
            volumeMounts:
            - name: volume-backup
              mountPath: /backup
            - name: etcd-peer-tls
              mountPath: /etc/kubernetes/pki/etcd-peer
            - name: etcd-server-ca
              mountPath: /etc/kubernetes/pki/etcd-ca
          restartPolicy: Never
          volumes:
          - name: volume-backup
            persistentVolumeClaim:
              claimName: etcd-backup-pvc
          - name: etcd-peer-tls
            secret:
              secretName: etcd-peer-tls
          - name: etcd-server-ca
            secret:
              secretName: etcd-server-ca
